version: '3'
services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      FLASK_ENV: development
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      FLASK_ENV: development