version: '3'
services:
  web:
    build:
        context: ./web
        dockerfile: Dockerfile
    ports:
      - "32769:8080"
    networks:
      - "envoymesh"
    environment:
      FLASK_ENV: development
    restart: always
    container_name: web_demo
networks:
  envoymesh: {}